[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SeoulTechPSE/EngNm/blob/master/ch02_code.ipynb)

# Chapter 2: Vectors, Matrices and Multidimensional Arrays

Creator: Robert Johansson, Updator: Kee-Youn Yoo

Updated source code listings for Numerical Python - A Practical Techniques Approach for Industry (ISBN 978-1-484205-54-9).

In [1]:
import numpy as np

## The Numpy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## Data types

In [10]:
d0 = np.array([1, 2, 3], dtype=np.int)

In [11]:
d1 = np.array([1, 2, 3], dtype=np.float)

In [12]:
d1.dtype

dtype('float64')

In [13]:
d2 = np.array([1, 2, 3], dtype=np.complex)

In [14]:
d2.dtype

dtype('complex128')

### Type casting

In [15]:
data = np.array([1, 2, 3], dtype=np.float)

In [16]:
data.dtype

dtype('float64')

In [17]:
data

array([1., 2., 3.])

In [18]:
data = np.array(data, dtype=np.int)

In [19]:
data.dtype

dtype('int32')

In [20]:
data

array([1, 2, 3])

In [21]:
data = np.array([1.6, 2, 3], dtype=np.float)

In [22]:
data.astype(np.int)

array([1, 2, 3])

### Type promotion

In [23]:
d1 = np.array([1, 2, 3], dtype=float)

In [24]:
d2 = np.array([1, 2, 3], dtype=complex)

In [25]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [26]:
(d1 + d2).dtype

dtype('complex128')

### Type-depending operation

In [27]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-27-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [28]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts 

In [29]:
data = np.array([1, 2, 3], dtype=complex); data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
data.real

array([1., 2., 3.])

In [31]:
data.imag

array([0., 0., 0.])

In [32]:
np.real(data)

array([1., 2., 3.])

In [33]:
np.imag(data)

array([0., 0., 0.])

### Order of array data in memory

* Multidimensional arrays are stored as contiguous data in memory. Consider the case of a two-dimensional array, $~$containing rows and columns: $~$One possible way to store this array as a consecutive sequence of values is to store the rows after each other, and another equally valid approach is to store the columns one after another. 

* The former is called row-major format and the latter is column-major format. Whether to use row-major or column-major is a matter of conventions, and the **row-major format** is used for example in the **C** programming language, and **Fortran** uses the **column-major format**. 

* A `NumPy` array can be specified to be stored in row-major format, using the keyword argument `order='C'`, and column-major format, using the keyword argument `order='F'`, when the array is created or reshaped. The default format is *row-major*. 

* In general, the `NumPy` array attribute `ndarray.strides` defines exactly how this mapping is done. The `strides` attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in `strides` is the factor by which the index for the corresponding axis is multiplied when calculating the *memory offset (in bytes)* for a given index expression.

In [34]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [35]:
data.strides

(12, 4)

In [36]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32, order='F')

In [37]:
data.strides

(4, 8)

## Creating arrays

### Arrays created from lists and other array-like objects

In [38]:
data = np.array([1, 2, 3, 4])

In [39]:
data.ndim

1

In [40]:
data.shape

(4,)

In [41]:
data = np.array([[1, 2], [3, 4]])

In [42]:
data.ndim

2

In [43]:
data.shape

(2, 2)

### Arrays filled with constant values

In [44]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

---

In [46]:
data = np.ones(4)

In [47]:
data.dtype

dtype('float64')

In [48]:
data = np.ones(4, dtype=np.int64)

In [49]:
data.dtype

dtype('int64')

---

In [50]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [51]:
np.full(10, 5.4) # slightly more efficient

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

---

In [52]:
x1 = np.empty(5); x1.fill(3.0)

In [53]:
x1

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [54]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.linspace(0, 10, 11) # generally recommended

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences 

In [56]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh grid arrays

In [57]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

In [58]:
X, Y = np.meshgrid(x, y)

In [59]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [60]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [61]:
Z = (X + Y)**2; Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

### Creating uninitialized arrays

In [62]:
x = np.empty(3, dtype=np.float); x

array([8.48798316e-314, 1.06099790e-313, 1.27319747e-313])

### Creating arrays with properties of other arrays

In [63]:
def f(x):    
    y = np.ones_like(x)    # compute with x and y    
    return y

x = np.array([[1, 2, 3], [4, 5, 6]])
y = f(x); y

array([[1, 1, 1],
       [1, 1, 1]])

### Creating matrix arrays

In [64]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [66]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing and slicing

### One-dimensional arrays

In [68]:
a = np.arange(0, 11); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a[0]

0

In [70]:
a[-1]

10

In [71]:
a[4]

4

---

In [72]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

---

In [74]:
a[:5]

array([0, 1, 2, 3, 4])

In [75]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [76]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### Multidimensional arrays

In [77]:
f = lambda m, n: n +10*m

In [78]:
A = np.fromfunction(f, (6, 6), dtype=int); A # please search for numpy.fromfunction at google

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

---

In [79]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [80]:
A[1, :]  # the second raw

array([10, 11, 12, 13, 14, 15])

In [81]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [82]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [83]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [84]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

* Subarrays that are extracted from arrays using slice operations are **alternative views** of the same underlying array data. That is, they are arrays that refer to the same data in memory as the original array, but with a different `strides` configuration. 

* When elements in a view are assigned new values, the values of the original
array are therefore also updated. For example,

In [85]:
B = A[1:5, 1:5]; B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [86]:
B[:, :] = 0; A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

When **a copy rather than a view** is needed, $~$the view can be copied explicitly by using
the `copy` method of the `ndarray` instance.

In [87]:
C = B[1:3, 1:3].copy(); C

array([[0, 0],
       [0, 0]])

In [88]:
C[:, :] = 1; C

array([[1, 1],
       [1, 1]])

In [89]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and boolean-valued indexing

In [90]:
A = np.linspace(0, 1, 11); A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [91]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [92]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

---

In [93]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [94]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

Unlike arrays created by using slices, $~$**the arrays returned using fancy indexing and Boolean-valued
indexing are not views**, but rather new independent arrays.

In [95]:
A = np.arange(10)

In [96]:
indices = [2, 4, 6]

In [97]:
B = A[indices]

In [98]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
A[indices] = -1; A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

---

In [100]:
A = np.arange(10)

In [101]:
B = A[A > 5]

In [102]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
A[A > 5] = -1; A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### Summery

<table>
<td><img src="./figs/array_indexing_01.png"></td>
<td><img src="./figs/array_indexing_02.png"></td>
<td><img src="./figs/array_indexing_03.png"></td>
<td><img src="./figs/array_indexing_04.png"></td>
</table>

<table>
<td><img src="./figs/array_indexing_05.png"></td>
<td><img src="./figs/array_indexing_06.png"></td>
<td><img src="./figs/array_indexing_07.png"></td>
<td><img src="./figs/array_indexing_08.png"></td>
</table>

<table>
<td><img src="./figs/array_indexing_09.png"></td>
<td><img src="./figs/array_indexing_10.png"></td>
<td><img src="./figs/array_indexing_11.png"></td>
<td><img src="./figs/array_indexing_12.png"></td>
</table>

## Reshaping and resizing

Reshaping an array does not require modifying the underlying array data; $~$it only changes in how the
data is interpreted, by redefining the array’s `strides` attribute.

In [104]:
data = np.array([[1, 2], [3, 4]])

In [105]:
data1 = np.reshape(data, (1, 4)); data1

array([[1, 2, 3, 4]])

In [106]:
data1[0, 1] = -1; data

array([[ 1, -1],
       [ 3,  4]])

In [107]:
data2 = data.reshape(4); data2

array([ 1, -1,  3,  4])

In [108]:
data2[1] = -2; data

array([[ 1, -2],
       [ 3,  4]])

---

In [109]:
data = np.array([[1, 2], [3, 4]])

In [110]:
data1 = np.ravel(data); data1

array([1, 2, 3, 4])

In [111]:
data1[0] = -1; data

array([[-1,  2],
       [ 3,  4]])

The `ndarray` method `flatten` perform the same function, but
returns a **copy** instead of a view.

In [112]:
data2 = data.flatten(); data2

array([-1,  2,  3,  4])

In [113]:
data2[0] = -2; data

array([[-1,  2],
       [ 3,  4]])

---

In [114]:
data = np.arange(0, 5); data.shape

(5,)

In [115]:
column = data[:, np.newaxis]; column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [116]:
column.shape

(5, 1)

In [117]:
row = data[np.newaxis, :]; row

array([[0, 1, 2, 3, 4]])

In [118]:
row.shape

(1, 5)

In [119]:
row[0, 0] = -1; data 

array([-1,  1,  2,  3,  4])

In [120]:
np.expand_dims(data, axis=1) 

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [121]:
row = np.expand_dims(data, axis=0)
row[0, 0] = -1; data

array([-1,  1,  2,  3,  4])

---

In [122]:
data = np.arange(5); data

array([0, 1, 2, 3, 4])

In [123]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [124]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [125]:
data = data[:, np.newaxis]; data.shape

(5, 1)

In [126]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [127]:
data1 = np.array([[1, 2], [3, 4]])

In [128]:
data2 = np.array([[5, 6]])

In [129]:
np.concatenate((data1, data2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
np.concatenate((data1, data2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorized expressions

### Arithmetic operations

In [131]:
x = np.array([[1, 2], [3, 4]])

In [132]:
y = np.array([[5, 6], [7, 8]])

In [133]:
x + y

array([[ 6,  8],
       [10, 12]])

In [134]:
y - x

array([[4, 4],
       [4, 4]])

In [135]:
x * y

array([[ 5, 12],
       [21, 32]])

In [136]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

---

In [137]:
x * 2

array([[2, 4],
       [6, 8]])

In [138]:
2**x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [139]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [140]:
(y / 2).dtype

dtype('float64')

---

<table>
<td><img src="./figs/array_broadcasting_1.png"></td>
</table>

<table>
<td><img src="./figs/array_broadcasting_2.png"></td>
</table>

In [141]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([1, 2, 3, 4])
x / y

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [142]:
z = np.array([[2, 4]]); z.shape

(1, 2)

In [143]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [144]:
zz = np.vstack((z, z)); zz

array([[2, 4],
       [2, 4]])

In [145]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

---

In [146]:
z = np.array([[2], [4]]); z.shape

(2, 1)

In [147]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [148]:
zz = np.concatenate([z, z], axis=1); zz

array([[2, 2],
       [4, 4]])

In [149]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

---

In [150]:
x = z = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x = x + y  # x is reassigned to a new array

In [151]:
x, z

(array([ 6,  8, 10, 12]), array([1, 2, 3, 4]))

In [152]:
x = z = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x += y  # the values of array x are updated in place

In [153]:
x, z

(array([ 6,  8, 10, 12]), array([ 6,  8, 10, 12]))

### Elementwise functions

In [154]:
x = np.linspace(-1, 1, 11); x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [155]:
y = np.sin(np.pi * x)

In [156]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [157]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [158]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---

In [159]:
def heaviside(x):
    return 1 if x > 0 else 0

In [160]:
heaviside(-1)

0

In [161]:
heaviside(1.5)

1

In [162]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [165]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [166]:
def heaviside(x):  # much better way
    return 1 * (x > 0)

heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

### Aggregate functions

In [167]:
data = np.random.normal(size=(15, 15))

In [168]:
np.mean(data)

-0.04457589445362472

In [169]:
data.mean()

-0.04457589445362472

---

In [170]:
data = np.random.normal(size=(5, 10, 15))

In [171]:
data.sum(axis=0).shape

(10, 15)

In [172]:
data.sum(axis=(0, 2)).shape

(10,)

In [173]:
data.sum()

-36.6749273319415

---

In [174]:
data = np.arange(1, 10).reshape(3, 3); data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
data.sum()

45

In [176]:
data.sum(axis=0)

array([12, 15, 18])

In [177]:
data.sum(axis=1)

array([ 6, 15, 24])

<table>
<td><img src="./figs/array_aggregation_1.png" width="300"></td>
<td><img src="./figs/array_aggregation_2.png" width="300"></td>
<td><img src="./figs/array_aggregation_3.png" width="300"></td>
</table>

### Boolean arrays and conditional expressions

In [178]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [179]:
a < b

array([ True,  True, False, False])

---

In [180]:
np.all(a < b)

False

In [181]:
np.any(a < b)

True

In [182]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding elements in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elements in b")
else:
    print("All elements in b are smaller than their corresponding elements in a")

Some elements in a are smaller than their corresponding elements in b


---

In [183]:
x = np.array([-2, -1, 0, 1, 2])

In [184]:
x > 0

array([False, False, False,  True,  True])

In [185]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [186]:
x * (x > 0)

array([0, 0, 0, 1, 2])

---

In [187]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

#   return height *np.logical_and(x >= position, x <= (position + width))                                       

In [188]:
x = np.linspace(-5, 5, 11)

In [189]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [190]:
pulse(x, position=1, height=2, width=2)

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0])

---

In [191]:
x = np.linspace(-4, 4, 9)

In [192]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [193]:
np.select([x < -1, x < 2, x>= 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [194]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

---

In [195]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [196]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [197]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

### Set operations

In [198]:
a = np.unique([1, 2, 3, 3]); a

array([1, 2, 3])

In [199]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]); b

array([2, 3, 4, 5, 6])

In [200]:
np.in1d(a, b)

array([False,  True,  True])

In [201]:
1 in a, 1 in b

(True, False)

In [202]:
np.all(np.in1d(a, b))  # to test if a is a subset of b

False

---

In [203]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [204]:
np.intersect1d(a, b)

array([2, 3])

In [205]:
np.setdiff1d(a, b)

array([1])

In [206]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [207]:
data = np.arange(9).reshape(3, 3); data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

---

In [209]:
data = np.random.randn(1, 2, 3, 4, 5)

In [210]:
data.shape

(1, 2, 3, 4, 5)

In [211]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [212]:
A = np.arange(1, 7).reshape(2, 3); A

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
B = np.arange(1, 7).reshape(3, 2); B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [215]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [216]:
A @ B  # python 3.5 above

array([[22, 28],
       [49, 64]])

---

In [217]:
A = np.arange(9).reshape(3, 3); A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [218]:
x = np.arange(3); x

array([0, 1, 2])

In [219]:
np.dot(A, x)

array([ 5, 14, 23])

In [220]:
A.dot(x)

array([ 5, 14, 23])

In [221]:
A @ x

array([ 5, 14, 23])

---

In [222]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [223]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [224]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [225]:
B @ A @ np.linalg.inv(B)

array([[-0.43509992, -1.29133677,  1.11525388],
       [-0.38795148, -0.2131471 ,  0.42747922],
       [ 0.19824381, -2.18837749,  1.15788821]])

---

In [226]:
A1 = np.matrix(A)
B1 = np.matrix(B)

In [227]:
Ap = B1 * A1 * B1.I

In [228]:
A2 = np.asmatrix(A)
B2 = np.asmatrix(B)

In [229]:
Ap = B2 * A2 * B2.I

In [230]:
Ap = np.asarray(Ap)

---

In [231]:
np.inner(x, x)

5

In [232]:
np.dot(x, x)

5

In [233]:
y = x[:, np.newaxis]; y

array([[0],
       [1],
       [2]])

In [234]:
np.dot(y.T, y)

array([[5]])

---

In [235]:
x = np.array([1, 2, 3])

In [236]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [237]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [238]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [239]:
np.kron(np.ones((2, 2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [240]:
np.kron(np.identity(2), np.ones((2, 2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

---

In [241]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [242]:
np.einsum("n,n", x, y)

70

In [243]:
np.inner(x, y)

70

In [244]:
A = np.arange(9).reshape(3, 3)
B = A.T

In [245]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [246]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

## Versions

In [247]:
print("numpy: ", np.__version__)

numpy:  1.19.2
